package com.tws.courier.domain.models

import com.google.gson.annotations.SerializedName

data class User(
    @SerializedName("id")
    var id : String,
    @SerializedName("user_ip")
    var user_ip : String,
    @SerializedName("username")
    var username : String,
    @SerializedName("slug") var slug : String,
    @SerializedName("email") var email : String,
    @SerializedName("mobile") var mobile : String,
    @SerializedName("password") var password : String,
    @SerializedName("first_name") var first_name : String,
    @SerializedName("last_name") var last_name : String,
    @SerializedName("profile_pic") var profile_pic : String,
    @SerializedName("company_name") var company_name : String,
    @SerializedName("requirement") var requirement : String,
    @SerializedName("comment") var comment : String,
    @SerializedName("lead_from") var lead_from : String,
    @SerializedName("followup_date") var followup_date : String,
    @SerializedName("is_pinned") var is_pinned : String,
    @SerializedName("dob") var dob : String,
    @SerializedName("about") var about : String,
    @SerializedName("doc_type") var doc_type : String,
    @SerializedName("doc_no") var doc_no : String,
    @SerializedName("gender") var gender : String,
    @SerializedName("status") var status : String,
    @SerializedName("parent_id") var parent_id : String,
    @SerializedName("affiliate_id") var affiliate_id : String,
    @SerializedName("email_verified") var email_verified : String,
    @SerializedName("mobile_verified") var mobile_verified : String,
    @SerializedName("google_id") var google_id : String,
    @SerializedName("fb_id") var fb_id : String,
    @SerializedName("address_id") var address_id : String,
    @SerializedName("ref_id") var ref_id : String,
    @SerializedName("pincode") var pincode : String,
    @SerializedName("firm_type") var firm_type : String,
    @SerializedName("address") var address : String,
    @SerializedName("gst_no") var gst_no : String,
    @SerializedName("bank_name") var bank_name : String,
    @SerializedName("account_holder_name") var account_holder_name : String,
    @SerializedName("account_no") var account_no : String,
    @SerializedName("confirm_accountno") var confirm_accountno : String,
    @SerializedName("ifsc_code") var ifsc_code : String,
    @SerializedName("phonePe") var phonePe : String,
    @SerializedName("google_pay") var google_pay : String,
    @SerializedName("paytm") var paytm : String,
    @SerializedName("pan_no") var pan_no : String,
    @SerializedName("user_type") var user_type : String,
    @SerializedName("seller_type") var seller_type : String,
    @SerializedName("order_count") var order_count : String,
    @SerializedName("wallet_amount") var wallet_amount : String,
    @SerializedName("total_paid") var total_paid : Double,
    @SerializedName("total_earn") var total_earn : String,
    @SerializedName("total_rider") var total_rider : String,
    @SerializedName("total_vehicle") var total_vehicle : String,
    @SerializedName("role_id") var role_id : String,
    @SerializedName("web_token_id") var web_token_id : String,
    @SerializedName("app_token_id") var app_token_id : String,
    @SerializedName("last_login_device") var last_login_device : String,
    @SerializedName("device_type") var device_type : String,
    @SerializedName("browser") var browser : String,
    @SerializedName("browser_version") var browser_version : String,
    @SerializedName("os") var os : String,
    @SerializedName("mobile_device") var mobile_device : String,
    @SerializedName("last_login_date") var last_login_date : String,
    @SerializedName("created_by") var created_by : String,
    @SerializedName("created_date") var created_date : String,
    @SerializedName("modified_by") var modified_by : String,
    @SerializedName("modified_date") var modified_date : String,
    @SerializedName("image") var image : String,
    @SerializedName("passbook_image") var passbook_image : String,
    @SerializedName("doc_front_image") var doc_front_image : String,
    @SerializedName("doc_back_image") var doc_back_image : String,
    @SerializedName("city") var city : String,
    @SerializedName("branch_name") var branch_name : String,
    @SerializedName("branch_city") var branch_city : String,
    @SerializedName("account_type") var account_type : String,
    @SerializedName("beneficiary_name") var beneficiary_name : String,
    @SerializedName("imagePath") var imagePath : String



)